language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jitrogith/travis-to-elasticbeanstalk -f Dockerfile.dev .

script:
  - docker run -e CI=true jitrogith/travis-to-elasticbeanstalk npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-537372604174"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
